apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobfit-dataset
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: jobfit-dataset
  storageClassName: ""
