apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobfit-runs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: jobfit-runs
  storageClassName: ""
